export const SERVICEDISCOVERED = "SERVICEDISCOVERED";
export const DISCONNECTIONHANDLER = "DISCONNECTIONHANDLER";
export const CONNECTIONSTATUS = "CONNECTIONSTATUS";
export const CONNECTIONINPROGRESS = "CONNECTIONINPROGRESS";
export const RESETSERVICES = "RESETSERVICES";
